# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_operation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynamic_operation.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x64ynamic_operation.proto\"\xe9\x06\n\rlocal_sources\x12\x0c\n\x04\x61rea\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x05\x12!\n\x02\x64g\x18\x03 \x03(\x0b\x32\x15.local_sources.DgType\x12#\n\x03\x65ss\x18\x04 \x03(\x0b\x32\x16.local_sources.EssType\x12!\n\x02pv\x18\x05 \x03(\x0b\x32\x15.local_sources.PvType\x12!\n\x02wp\x18\x06 \x03(\x0b\x32\x15.local_sources.WpType\x12,\n\x07load_ac\x18\x07 \x03(\x0b\x32\x1b.local_sources.Load_AC_Type\x12,\n\x07load_dc\x18\x08 \x03(\x0b\x32\x1b.local_sources.Load_DC_Type\x12*\n\x03\x62ic\x18\t \x03(\x0b\x32\x1d.local_sources.Convertor_Type\x12\x1a\n\x12TIME_STAMP_COMMAND\x18\n \x01(\x05\x1aX\n\x06\x44gType\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nGEN_STATUS\x18\x02 \x03(\x08\x12\n\n\x02PG\x18\x03 \x03(\x05\x12\n\n\x02RG\x18\x04 \x03(\x05\x12\x16\n\x0e\x43OMMAND_STATUS\x18\x05 \x03(\x08\x1aN\n\x07\x45ssType\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x12\n\nESS_STATUS\x18\x02 \x03(\x08\x12\x0b\n\x03SOC\x18\x03 \x03(\x02\x12\n\n\x02PG\x18\x04 \x03(\x05\x12\n\n\x02RG\x18\x05 \x03(\x05\x1a\x37\n\x06PvType\x12\x0b\n\x03NPV\x18\x01 \x03(\x05\x12\n\n\x02PG\x18\x02 \x03(\x02\x12\x14\n\x0c\x43OMMAND_CURT\x18\x03 \x03(\x05\x1a\x37\n\x06WpType\x12\x0b\n\x03NWP\x18\x01 \x03(\x05\x12\n\n\x02PG\x18\x02 \x03(\x02\x12\x14\n\x0c\x43OMMAND_CURT\x18\x03 \x03(\x05\x1aL\n\x0cLoad_AC_Type\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0e\n\x06STATUS\x18\x02 \x03(\x08\x12\n\n\x02PD\x18\x03 \x03(\x05\x12\x14\n\x0c\x43OMMAND_SHED\x18\x04 \x03(\x02\x1aL\n\x0cLoad_DC_Type\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0e\n\x06STATUS\x18\x02 \x03(\x08\x12\n\n\x02PD\x18\x03 \x03(\x05\x12\x14\n\x0c\x43OMMAND_SHED\x18\x04 \x03(\x02\x1aL\n\x0e\x43onvertor_Type\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0e\n\x06STATUS\x18\x02 \x03(\x08\x12\x0e\n\x06PAC2DC\x18\x03 \x03(\x02\x12\x0e\n\x06PDC2AC\x18\x04 \x03(\x02\x62\x06proto3')
)




_LOCAL_SOURCES_DGTYPE = _descriptor.Descriptor(
  name='DgType',
  full_name='local_sources.DgType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='local_sources.DgType.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GEN_STATUS', full_name='local_sources.DgType.GEN_STATUS', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='local_sources.DgType.PG', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RG', full_name='local_sources.DgType.RG', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_STATUS', full_name='local_sources.DgType.COMMAND_STATUS', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=473,
)

_LOCAL_SOURCES_ESSTYPE = _descriptor.Descriptor(
  name='EssType',
  full_name='local_sources.EssType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='local_sources.EssType.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ESS_STATUS', full_name='local_sources.EssType.ESS_STATUS', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOC', full_name='local_sources.EssType.SOC', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='local_sources.EssType.PG', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RG', full_name='local_sources.EssType.RG', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=553,
)

_LOCAL_SOURCES_PVTYPE = _descriptor.Descriptor(
  name='PvType',
  full_name='local_sources.PvType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NPV', full_name='local_sources.PvType.NPV', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='local_sources.PvType.PG', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_CURT', full_name='local_sources.PvType.COMMAND_CURT', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=610,
)

_LOCAL_SOURCES_WPTYPE = _descriptor.Descriptor(
  name='WpType',
  full_name='local_sources.WpType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NWP', full_name='local_sources.WpType.NWP', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='local_sources.WpType.PG', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_CURT', full_name='local_sources.WpType.COMMAND_CURT', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=667,
)

_LOCAL_SOURCES_LOAD_AC_TYPE = _descriptor.Descriptor(
  name='Load_AC_Type',
  full_name='local_sources.Load_AC_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='local_sources.Load_AC_Type.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='STATUS', full_name='local_sources.Load_AC_Type.STATUS', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PD', full_name='local_sources.Load_AC_Type.PD', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_SHED', full_name='local_sources.Load_AC_Type.COMMAND_SHED', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=745,
)

_LOCAL_SOURCES_LOAD_DC_TYPE = _descriptor.Descriptor(
  name='Load_DC_Type',
  full_name='local_sources.Load_DC_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='local_sources.Load_DC_Type.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='STATUS', full_name='local_sources.Load_DC_Type.STATUS', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PD', full_name='local_sources.Load_DC_Type.PD', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_SHED', full_name='local_sources.Load_DC_Type.COMMAND_SHED', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=747,
  serialized_end=823,
)

_LOCAL_SOURCES_CONVERTOR_TYPE = _descriptor.Descriptor(
  name='Convertor_Type',
  full_name='local_sources.Convertor_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='local_sources.Convertor_Type.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='STATUS', full_name='local_sources.Convertor_Type.STATUS', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PAC2DC', full_name='local_sources.Convertor_Type.PAC2DC', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PDC2AC', full_name='local_sources.Convertor_Type.PDC2AC', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=825,
  serialized_end=901,
)

_LOCAL_SOURCES = _descriptor.Descriptor(
  name='local_sources',
  full_name='local_sources',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='area', full_name='local_sources.area', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='local_sources.time_stamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dg', full_name='local_sources.dg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ess', full_name='local_sources.ess', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pv', full_name='local_sources.pv', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wp', full_name='local_sources.wp', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_ac', full_name='local_sources.load_ac', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_dc', full_name='local_sources.load_dc', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bic', full_name='local_sources.bic', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TIME_STAMP_COMMAND', full_name='local_sources.TIME_STAMP_COMMAND', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LOCAL_SOURCES_DGTYPE, _LOCAL_SOURCES_ESSTYPE, _LOCAL_SOURCES_PVTYPE, _LOCAL_SOURCES_WPTYPE, _LOCAL_SOURCES_LOAD_AC_TYPE, _LOCAL_SOURCES_LOAD_DC_TYPE, _LOCAL_SOURCES_CONVERTOR_TYPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=901,
)

_LOCAL_SOURCES_DGTYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_ESSTYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_PVTYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_WPTYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_LOAD_AC_TYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_LOAD_DC_TYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES_CONVERTOR_TYPE.containing_type = _LOCAL_SOURCES
_LOCAL_SOURCES.fields_by_name['dg'].message_type = _LOCAL_SOURCES_DGTYPE
_LOCAL_SOURCES.fields_by_name['ess'].message_type = _LOCAL_SOURCES_ESSTYPE
_LOCAL_SOURCES.fields_by_name['pv'].message_type = _LOCAL_SOURCES_PVTYPE
_LOCAL_SOURCES.fields_by_name['wp'].message_type = _LOCAL_SOURCES_WPTYPE
_LOCAL_SOURCES.fields_by_name['load_ac'].message_type = _LOCAL_SOURCES_LOAD_AC_TYPE
_LOCAL_SOURCES.fields_by_name['load_dc'].message_type = _LOCAL_SOURCES_LOAD_DC_TYPE
_LOCAL_SOURCES.fields_by_name['bic'].message_type = _LOCAL_SOURCES_CONVERTOR_TYPE
DESCRIPTOR.message_types_by_name['local_sources'] = _LOCAL_SOURCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

local_sources = _reflection.GeneratedProtocolMessageType('local_sources', (_message.Message,), dict(

  DgType = _reflection.GeneratedProtocolMessageType('DgType', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_DGTYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.DgType)
    ))
  ,

  EssType = _reflection.GeneratedProtocolMessageType('EssType', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_ESSTYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.EssType)
    ))
  ,

  PvType = _reflection.GeneratedProtocolMessageType('PvType', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_PVTYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.PvType)
    ))
  ,

  WpType = _reflection.GeneratedProtocolMessageType('WpType', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_WPTYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.WpType)
    ))
  ,

  Load_AC_Type = _reflection.GeneratedProtocolMessageType('Load_AC_Type', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_LOAD_AC_TYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.Load_AC_Type)
    ))
  ,

  Load_DC_Type = _reflection.GeneratedProtocolMessageType('Load_DC_Type', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_LOAD_DC_TYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.Load_DC_Type)
    ))
  ,

  Convertor_Type = _reflection.GeneratedProtocolMessageType('Convertor_Type', (_message.Message,), dict(
    DESCRIPTOR = _LOCAL_SOURCES_CONVERTOR_TYPE,
    __module__ = 'dynamic_operation_pb2'
    # @@protoc_insertion_point(class_scope:local_sources.Convertor_Type)
    ))
  ,
  DESCRIPTOR = _LOCAL_SOURCES,
  __module__ = 'dynamic_operation_pb2'
  # @@protoc_insertion_point(class_scope:local_sources)
  ))
_sym_db.RegisterMessage(local_sources)
_sym_db.RegisterMessage(local_sources.DgType)
_sym_db.RegisterMessage(local_sources.EssType)
_sym_db.RegisterMessage(local_sources.PvType)
_sym_db.RegisterMessage(local_sources.WpType)
_sym_db.RegisterMessage(local_sources.Load_AC_Type)
_sym_db.RegisterMessage(local_sources.Load_DC_Type)
_sym_db.RegisterMessage(local_sources.Convertor_Type)


# @@protoc_insertion_point(module_scope)
