# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: information_exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='information_exchange.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1ainformation_exchange.proto\"\xff\x06\n\x14informaiton_exchange\x12\x0c\n\x04\x41REA\x18\x01 \x01(\x05\x12\x12\n\nTIME_STAMP\x18\x02 \x01(\x05\x12(\n\x02\x64g\x18\x03 \x03(\x0b\x32\x1c.informaiton_exchange.DgType\x12*\n\x03\x65ss\x18\x04 \x03(\x0b\x32\x1d.informaiton_exchange.EssType\x12(\n\x02pv\x18\x05 \x03(\x0b\x32\x1c.informaiton_exchange.PvType\x12(\n\x02wp\x18\x06 \x03(\x0b\x32\x1c.informaiton_exchange.WpType\x12\x33\n\x07load_ac\x18\x07 \x03(\x0b\x32\".informaiton_exchange.Load_AC_Type\x12\x33\n\x07load_dc\x18\x08 \x03(\x0b\x32\".informaiton_exchange.Load_DC_Type\x12\x31\n\x03\x62ic\x18\t \x03(\x0b\x32$.informaiton_exchange.Convertor_Type\x12\x0b\n\x03PMG\x18\n \x01(\x05\x12\x0c\n\x04V_DC\x18\x0b \x01(\x02\x12\x1a\n\x12TIME_STAMP_COMMAND\x18\x0c \x01(\x05\x1aO\n\x06\x44gType\x12\r\n\x05\x44G_ID\x18\x01 \x01(\x05\x12\x12\n\nGEN_STATUS\x18\x02 \x01(\x08\x12\n\n\x02PG\x18\x03 \x01(\x05\x12\n\n\x02QG\x18\x04 \x01(\x05\x12\n\n\x02RG\x18\x05 \x01(\x05\x1aR\n\x07\x45ssType\x12\x0e\n\x06\x45SS_ID\x18\x01 \x01(\x05\x12\x12\n\nESS_STATUS\x18\x02 \x01(\x08\x12\x0b\n\x03SOC\x18\x03 \x01(\x02\x12\n\n\x02PG\x18\x04 \x01(\x05\x12\n\n\x02RG\x18\x05 \x01(\x05\x1a\x37\n\x06PvType\x12\x0b\n\x03NPV\x18\x01 \x01(\x05\x12\n\n\x02PG\x18\x02 \x01(\x02\x12\x14\n\x0c\x43OMMAND_CURT\x18\x03 \x01(\x05\x1a\x37\n\x06WpType\x12\x0b\n\x03NWP\x18\x01 \x01(\x05\x12\n\n\x02PG\x18\x02 \x01(\x02\x12\x14\n\x0c\x43OMMAND_CURT\x18\x03 \x01(\x05\x1a<\n\x0cLoad_AC_Type\x12\n\n\x02PD\x18\x01 \x01(\x02\x12\n\n\x02QD\x18\x02 \x01(\x02\x12\x14\n\x0c\x43OMMAND_SHED\x18\x03 \x01(\x02\x1a\x30\n\x0cLoad_DC_Type\x12\n\n\x02PD\x18\x01 \x01(\x02\x12\x14\n\x0c\x43OMMAND_SHED\x18\x02 \x01(\x02\x1a@\n\x0e\x43onvertor_Type\x12\x0e\n\x06STATUS\x18\x01 \x01(\x08\x12\x0e\n\x06PAC2DC\x18\x02 \x01(\x02\x12\x0e\n\x06PDC2AC\x18\x03 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INFORMAITON_EXCHANGE_DGTYPE = _descriptor.Descriptor(
  name='DgType',
  full_name='informaiton_exchange.DgType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DG_ID', full_name='informaiton_exchange.DgType.DG_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GEN_STATUS', full_name='informaiton_exchange.DgType.GEN_STATUS', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='informaiton_exchange.DgType.PG', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QG', full_name='informaiton_exchange.DgType.QG', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RG', full_name='informaiton_exchange.DgType.RG', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=550,
)

_INFORMAITON_EXCHANGE_ESSTYPE = _descriptor.Descriptor(
  name='EssType',
  full_name='informaiton_exchange.EssType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ESS_ID', full_name='informaiton_exchange.EssType.ESS_ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ESS_STATUS', full_name='informaiton_exchange.EssType.ESS_STATUS', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SOC', full_name='informaiton_exchange.EssType.SOC', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='informaiton_exchange.EssType.PG', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RG', full_name='informaiton_exchange.EssType.RG', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=634,
)

_INFORMAITON_EXCHANGE_PVTYPE = _descriptor.Descriptor(
  name='PvType',
  full_name='informaiton_exchange.PvType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NPV', full_name='informaiton_exchange.PvType.NPV', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='informaiton_exchange.PvType.PG', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_CURT', full_name='informaiton_exchange.PvType.COMMAND_CURT', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=636,
  serialized_end=691,
)

_INFORMAITON_EXCHANGE_WPTYPE = _descriptor.Descriptor(
  name='WpType',
  full_name='informaiton_exchange.WpType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NWP', full_name='informaiton_exchange.WpType.NWP', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PG', full_name='informaiton_exchange.WpType.PG', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_CURT', full_name='informaiton_exchange.WpType.COMMAND_CURT', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=748,
)

_INFORMAITON_EXCHANGE_LOAD_AC_TYPE = _descriptor.Descriptor(
  name='Load_AC_Type',
  full_name='informaiton_exchange.Load_AC_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PD', full_name='informaiton_exchange.Load_AC_Type.PD', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QD', full_name='informaiton_exchange.Load_AC_Type.QD', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_SHED', full_name='informaiton_exchange.Load_AC_Type.COMMAND_SHED', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=810,
)

_INFORMAITON_EXCHANGE_LOAD_DC_TYPE = _descriptor.Descriptor(
  name='Load_DC_Type',
  full_name='informaiton_exchange.Load_DC_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PD', full_name='informaiton_exchange.Load_DC_Type.PD', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='COMMAND_SHED', full_name='informaiton_exchange.Load_DC_Type.COMMAND_SHED', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=812,
  serialized_end=860,
)

_INFORMAITON_EXCHANGE_CONVERTOR_TYPE = _descriptor.Descriptor(
  name='Convertor_Type',
  full_name='informaiton_exchange.Convertor_Type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='STATUS', full_name='informaiton_exchange.Convertor_Type.STATUS', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PAC2DC', full_name='informaiton_exchange.Convertor_Type.PAC2DC', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PDC2AC', full_name='informaiton_exchange.Convertor_Type.PDC2AC', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=862,
  serialized_end=926,
)

_INFORMAITON_EXCHANGE = _descriptor.Descriptor(
  name='informaiton_exchange',
  full_name='informaiton_exchange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AREA', full_name='informaiton_exchange.AREA', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TIME_STAMP', full_name='informaiton_exchange.TIME_STAMP', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dg', full_name='informaiton_exchange.dg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ess', full_name='informaiton_exchange.ess', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pv', full_name='informaiton_exchange.pv', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wp', full_name='informaiton_exchange.wp', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_ac', full_name='informaiton_exchange.load_ac', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='load_dc', full_name='informaiton_exchange.load_dc', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bic', full_name='informaiton_exchange.bic', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PMG', full_name='informaiton_exchange.PMG', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='V_DC', full_name='informaiton_exchange.V_DC', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TIME_STAMP_COMMAND', full_name='informaiton_exchange.TIME_STAMP_COMMAND', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INFORMAITON_EXCHANGE_DGTYPE, _INFORMAITON_EXCHANGE_ESSTYPE, _INFORMAITON_EXCHANGE_PVTYPE, _INFORMAITON_EXCHANGE_WPTYPE, _INFORMAITON_EXCHANGE_LOAD_AC_TYPE, _INFORMAITON_EXCHANGE_LOAD_DC_TYPE, _INFORMAITON_EXCHANGE_CONVERTOR_TYPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=926,
)

_INFORMAITON_EXCHANGE_DGTYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_ESSTYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_PVTYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_WPTYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_LOAD_AC_TYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_LOAD_DC_TYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE_CONVERTOR_TYPE.containing_type = _INFORMAITON_EXCHANGE
_INFORMAITON_EXCHANGE.fields_by_name['dg'].message_type = _INFORMAITON_EXCHANGE_DGTYPE
_INFORMAITON_EXCHANGE.fields_by_name['ess'].message_type = _INFORMAITON_EXCHANGE_ESSTYPE
_INFORMAITON_EXCHANGE.fields_by_name['pv'].message_type = _INFORMAITON_EXCHANGE_PVTYPE
_INFORMAITON_EXCHANGE.fields_by_name['wp'].message_type = _INFORMAITON_EXCHANGE_WPTYPE
_INFORMAITON_EXCHANGE.fields_by_name['load_ac'].message_type = _INFORMAITON_EXCHANGE_LOAD_AC_TYPE
_INFORMAITON_EXCHANGE.fields_by_name['load_dc'].message_type = _INFORMAITON_EXCHANGE_LOAD_DC_TYPE
_INFORMAITON_EXCHANGE.fields_by_name['bic'].message_type = _INFORMAITON_EXCHANGE_CONVERTOR_TYPE
DESCRIPTOR.message_types_by_name['informaiton_exchange'] = _INFORMAITON_EXCHANGE

informaiton_exchange = _reflection.GeneratedProtocolMessageType('informaiton_exchange', (_message.Message,), dict(

  DgType = _reflection.GeneratedProtocolMessageType('DgType', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_DGTYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.DgType)
    ))
  ,

  EssType = _reflection.GeneratedProtocolMessageType('EssType', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_ESSTYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.EssType)
    ))
  ,

  PvType = _reflection.GeneratedProtocolMessageType('PvType', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_PVTYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.PvType)
    ))
  ,

  WpType = _reflection.GeneratedProtocolMessageType('WpType', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_WPTYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.WpType)
    ))
  ,

  Load_AC_Type = _reflection.GeneratedProtocolMessageType('Load_AC_Type', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_LOAD_AC_TYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.Load_AC_Type)
    ))
  ,

  Load_DC_Type = _reflection.GeneratedProtocolMessageType('Load_DC_Type', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_LOAD_DC_TYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.Load_DC_Type)
    ))
  ,

  Convertor_Type = _reflection.GeneratedProtocolMessageType('Convertor_Type', (_message.Message,), dict(
    DESCRIPTOR = _INFORMAITON_EXCHANGE_CONVERTOR_TYPE,
    __module__ = 'information_exchange_pb2'
    # @@protoc_insertion_point(class_scope:informaiton_exchange.Convertor_Type)
    ))
  ,
  DESCRIPTOR = _INFORMAITON_EXCHANGE,
  __module__ = 'information_exchange_pb2'
  # @@protoc_insertion_point(class_scope:informaiton_exchange)
  ))
_sym_db.RegisterMessage(informaiton_exchange)
_sym_db.RegisterMessage(informaiton_exchange.DgType)
_sym_db.RegisterMessage(informaiton_exchange.EssType)
_sym_db.RegisterMessage(informaiton_exchange.PvType)
_sym_db.RegisterMessage(informaiton_exchange.WpType)
_sym_db.RegisterMessage(informaiton_exchange.Load_AC_Type)
_sym_db.RegisterMessage(informaiton_exchange.Load_DC_Type)
_sym_db.RegisterMessage(informaiton_exchange.Convertor_Type)


# @@protoc_insertion_point(module_scope)
